### ISSUE TITLE
The paper or report about model.

### ISSUE THREAD

**Issue by lucky-szj** [hubutui/Gleason#4]
Where I can find the report or paper about this model?My wechat is szj_lucky0904,hopely receive your reply! Thanks!

**Comment by hubutui** [comment]
This repo contains all the codes I used in the challenge. There is nothing new or tricky. It's a simple appplication of PSPNet. The train script comes from torchvision's [reference](https://github.com/pytorch/vision/tree/master/references/segmentation).

**Comment by lucky-szj** [comment]
ok,Thanks!

**Comment by lucky-szj** [comment]
`| distributed init (rank 0): 10.212.66.4
Traceback (most recent call last):
  File "/gs/home/sunzhongjie/Gleason-master/train.py", line 237, in <module>
    main(args)
  File "/gs/home/sunzhongjie/Gleason-master/train.py", line 100, in main
    utils.init_distributed_mode(args)
  File "/gs/home/sunzhongjie/Gleason-master/utils.py", line 298, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/gs/home/sunzhongjie/.conda/envs/testenv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 396, in init_process_group
    rendezvous_iterator = rendezvous(init_method, rank, world_size)
  File "/gs/home/sunzhongjie/.conda/envs/testenv/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 73, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for ://
`

Hu yujin,Did you kown the reason of this question?

**Comment by hubutui** [comment]
@lucky-szj I didn't use distributed training.
